{% set version = "3.0.0b1" %}

package:
  name: cantera-recipe
  version: {{ version }}

source:
  # url: https://github.com/Cantera/cantera/archive/v{{ version }}.tar.gz
  url: https://github.com/Cantera/cantera/archive/43fca5354.tar.gz
  sha256: e267b3a2dfd064af65155a8987972ee2287eda2e42f5d2d8f78699da68679454

build:
  number: 0
  include_recipe: True
  skip: True  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}

outputs:
  - name: libcantera
    script: build_lib.sh
    build:
      skip: True  # [not osx]
    requirements:
      build:
        - python {{ python }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python {{ python }}
      run:
        - python {{ python }}
    test:
      files:
        - test-lib
      commands:
        - echo "STARTING TESTS"
        - ./test-lib/test-mwe.sh
        - echo "FINISHED TESTS"

about:
  home: https://cantera.org
  summary: "Chemical kinetics, thermodynamics, and transport tool suite"
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  dev_url: https://github.com/cantera/cantera
  description: Cantera is an open-source suite of tools for problems involving chemical kinetics, thermodynamics, and transport processes
  doc_url: https://cantera.org/documentation

extra:
  feedstock-name: cantera
  recipe-maintainers:
    - inducer
    - bryanwweber
    - matthiasdiener
